apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: kubeops
  name: kubeops
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kubeops
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: kubeops
    spec:
      containers:
        - image: pipper/kubeops:0.1.0
          name: kubeops
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
